In [10]:
 ['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [2]:
type(lambda x: x+1) 

function

In [7]:
import time
time.gmtime(0)

time.struct_time(tm_year=1970, tm_mon=1, tm_mday=1, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=1, tm_isdst=0)

In [8]:
 [x**2 for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [41]:
import numpy as np
r=np.arange(64).reshape(8,8)
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

 - eg - tmp[::7]
- array([ 0,  7, 14, 21, 28, 35])

- Slicing/Indexing is represented as **i:j:k, where i = from, j = to and k = step.**
- Thus, 5:10:2 would mean from element 5th to the 10th, give me elements every 2 steps.
- If i is not present, it is assumed to be from the beginning of the array. If j is not present, it is assumed to be until the end of the array. If k is not present it is assumed to have an step of 1 (all the elements in the range).

In [42]:
r[::,::7]

array([[ 0,  7],
       [ 8, 15],
       [16, 23],
       [24, 31],
       [32, 39],
       [40, 47],
       [48, 55],
       [56, 63]])

In [44]:
r.reshape(64)[::7]


array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63])

In [47]:
r[0:8,::-7]


array([[ 7,  0],
       [15,  8],
       [23, 16],
       [31, 24],
       [39, 32],
       [47, 40],
       [55, 48],
       [63, 56]])

In [49]:
r[::8]

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [50]:
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [54]:
r[[2,3],[2,3]]

array([18, 27])

In [55]:
r[2:4,2:4]

array([[18, 19],
       [26, 27]])